title: Rónai Fanni Portfólió
description: Egyetemi kurzusaim során szerzett készségeim gyakorlása, illetve továbbfejlesztése céljából készítettem ezeket a projektmunkákat.
remote_theme: pages-themes/slate@v0.2.0
